apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.0.0
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--web.enable-lifecycle'
        ports:
        - name: web
          containerPort: 9090
       
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: rules-volume
          mountPath: /etc/prometheus-rules
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-configmap
      - name: rules-volume
        configMap:
          name: prometheus-rules
        #hostPath:
        #  path: /etc/ssl/etcd/
      - name: prometheus-data
        emptyDir: {}
      #- name: prometheus-data
      #  rbd:
      #    fsType: ext4
      #    image: prometheus-data
      #    keyring: /etc/ceph/keyring
      #    monitors:
      #    - ceph-mon.ceph.svc.cluster.local
      #    pool: rbd
      #    secretRef:
      #      name: ceph-secret
      #    user: admin
