groups:
- name: es-logs-status.rules
  rules:
  - alert: ESLogsStatus
    expr: absent(es_cluster_status{cluster="es-logs"}) or avg(es_cluster_status{cluster="es-logs"})
      != 0
    for: 2m
    labels:
      severity: page
    annotations:
      DESCRIPTION: '{{$labels.instance}}: "es-logs" Elasticsearch cluster status is
        not green (or 0), current value is: {{ $value }}'
      SUMMARY: '{{$labels.instance}}: "es-logs" Elasticsearch cluster status is not
        green'
